export default {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    REGISTER_CUSTOMER: 'REGISTER_CUSTOMER',
    REGISTER_CUSTOMER_REQUEST: 'REGISTER_CUSTOMER_REQUEST',
    REGISTER_CUSTOMER_SUCCESS: 'REGISTER_CUSTOMER_SUCCESS',
    REGISTER_CUSTOMER_FAILURE: 'REGISTER_CUSTOMER_FAILURE',
}