const Images = {
  welcome_bg: require('../../assets/images/welcome.png'),
  logo: require('../../assets/images/logo.png'),
  arrow_left: require('../../assets/images/arrow-left.png'),
  auth_bg: require('../../assets/images/auth_bg.png'),
  green_bg: require('../../assets/images/green_bg.png'),
  btn_facebook: require('../../assets/images/facebook.png'),
  btn_twitter: require('../../assets/images/twitter.png'),
  btn_google: require('../../assets/images/google.png'),
  male: require('../../assets/images/male.png'),
  female: require('../../assets/images/female.png'),
  search: require('../../assets/images/search.png'),
  setting: require('../../assets/images/setting.png'),
  notification: require('../../assets/images/notification.png'),
  friend: require('../../assets/images/friend.png'),
  messageAvatar: require('../../assets/images/message-avatar.png'),
  house: require('../../assets/images/house.png'),
  profile_avatar: require('../../assets/images/profile_avatar.png'),
  icon_bedroom: require('../../assets/images/icon_bedroom.png'),
  icon_bathroom: require('../../assets/images/icon_bathroom.png'),
  icon_distance: require('../../assets/images/icon_distance.png'),
  icon_tick: require('../../assets/images/icon_tick.png'),
  icon_send: require('../../assets/images/icon_send.png'),
  icon_smile: require('../../assets/images/icon_smile.png'),
  icon_explore_inactive: require('../../assets/images/icon_explore_inactive.png'),
  icon_explore_active: require('../../assets/images/icon_explore_active.png'),
  icon_houses_inactive: require('../../assets/images/icon_houses_inactive.png'),
  icon_houses_active: require('../../assets/images/icon_houses_active.png'),
  icon_dating_inactive: require('../../assets/images/icon_dating_inactive.png'),
  icon_dating_active: require('../../assets/images/icon_dating_active.png'),
  icon_profile_inactive: require('../../assets/images/icon_profile_inactive.png'),
  icon_profile_active: require('../../assets/images/icon_profile_active.png'),
  icon_employments_inactive: require('../../assets/images/icon_employments_inactive.png'),
  icon_employments_active: require('../../assets/images/icon_employments_active.png'),
  icon_search: require('../../assets/images/icon_search.png'),
  arrow_left: require('../../assets/images/arrow-left.png'),
  setting_profile: require('../../assets/images/setting_profile.png'),
  green_bubble: require('../../assets/images/green_bubble.png'),
  white_bubble: require('../../assets/images/white_bubble.png'),
  gray_bg: require('../../assets/images/gray_bg.png')
}

export default Images;